# Generated by Django 5.0 on 2024-11-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Patient", "0005_remove_patient_city_patient_current_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.CharField(max_length=50)),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("appointment_time", models.TimeField(blank=True, null=True)),
                ("appointment_adress", models.CharField(max_length=60)),
                ("accompany", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Patient.patient",
                    ),
                ),
            ],
            options={
                "db_table": "appointment",
            },
        ),
    ]
