# Generated by Django 5.0 on 2024-11-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Patient", "0005_remove_patient_city_patient_current_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(blank=True, max_length=50, null=True)),
                ("doctor", models.CharField(blank=True, max_length=50, null=True)),
                ("operation_place", models.DateField(blank=True, null=True)),
                ("operation_date", models.DateField(blank=True, null=True)),
                (
                    "operation_costs",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Patient.patient",
                    ),
                ),
            ],
            options={
                "db_table": "operation",
            },
        ),
    ]
