# Generated by Django 5.0 on 2024-11-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Operation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="doctor",
            new_name="doctor_or_hospital",
        ),
    ]
