# Generated by Django 5.0 on 2024-11-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Operation", "0002_rename_doctor_operation_doctor_or_hospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="operation_place",
            field=models.CharField(blank=True, null=True),
        ),
    ]
