# Generated by Django 5.0 on 2024-11-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Patient", "0005_remove_patient_city_patient_current_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=50)),
                ("medication_type", models.CharField(max_length=50)),
                ("medicametion_costs", models.CharField(max_length=20)),
                (
                    "when_to_use",
                    models.CharField(
                        choices=[("m", "morning"), ("m", "midday"), ("n", "night")],
                        max_length=1,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Patient.patient",
                    ),
                ),
            ],
            options={
                "db_table": "medications",
            },
        ),
    ]
