# Generated by Django 5.0 on 2024-11-21 18:56

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Medication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="when_to_use",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("m", "morning"), ("m", "midday"), ("n", "night")],
                max_length=1,
            ),
        ),
    ]
