# Generated by Django 5.0 on 2024-11-21 19:01

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medication", "0002_alter_medication_when_to_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="medicametion_costs",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="medication",
            name="when_to_use",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("m", "morning"), ("m", "midday"), ("n", "night")],
                max_length=5,
            ),
        ),
    ]
