# Generated by Django 5.0 on 2024-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
