# Generated by Django 5.0 on 2024-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0002_patient_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="city",
            field=models.CharField(
                blank=True, choices=[("Amude", "Berlin")], null=True
            ),
        ),
    ]
