# Generated by Django 5.0 on 2024-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0003_patient_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[("Amude", "Amude"), ("Berlin", "Berlin")],
                null=True,
            ),
        ),
    ]
