# Generated by Django 5.0 on 2024-11-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0004_alter_patient_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="city",
        ),
        migrations.AddField(
            model_name="patient",
            name="current_city",
            field=models.CharField(
                blank=True,
                choices=[("Amude", "Amude"), ("Berlin", "Berlin")],
                max_length=20,
                null=True,
            ),
        ),
    ]
