# Generated by Django 5.0 on 2024-11-20 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Patient", "0005_remove_patient_city_patient_current_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(max_length=50)),
                (
                    "hereditary",
                    models.CharField(choices=[("y", "yes"), ("n", "no")], max_length=1),
                ),
                ("disease_start_date", models.DateField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Patient.patient",
                    ),
                ),
            ],
            options={
                "db_table": "diseases",
            },
        ),
    ]
