# Generated by Django 5.0 on 2024-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Disease", "0001_initial"),
        ("Medication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="medications",
            field=models.ManyToManyField(
                related_name="disease", to="Medication.medication"
            ),
        ),
    ]
