# Generated by Django 5.0 on 2024-11-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Allergy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergy",
            name="seasonal",
            field=models.CharField(
                choices=[("y", "Yes"), ("n", "No")], default="n", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="allergy",
            name="which_season",
            field=models.CharField(
                blank=True,
                choices=[
                    ("s", "Summer"),
                    ("w", "Winter"),
                    ("a", "Autumn"),
                    ("sp", "Spring"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="hereditary",
            field=models.CharField(choices=[("y", "Yes"), ("n", "No")], max_length=1),
        ),
    ]
