# Generated by Django 5.0 on 2024-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Allergy", "0002_allergy_seasonal_allergy_which_season_and_more"),
        ("Medication", "0003_alter_medication_medicametion_costs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergy",
            name="medications",
            field=models.ManyToManyField(
                related_name="allergy", to="Medication.medication"
            ),
        ),
    ]
